label: 'Sylwadau diweddar'
display:
  default:
    display_options:
      title: 'Sylwadau diweddar'
      empty:
        area_text_custom:
          content: 'Dim sylwadau ar gael'
  block_1:
    display_title: Bloc
    display_options:
      block_description: 'Sylwadau diweddar'
