display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Ceisio
          reset_button_label: Ailosod
          exposed_sorts_label: 'Dosbarthu drwy'
      filters:
        access:
          expose:
            label: 'Mynediad diwethaf'
            description: 'Mae defnyddiwr yn cael ei gysidro ar-lein am hyn o maser ar ôl iddynt weld tudlaen.'
      title: 'Pwy sydd ar-lein'
  who_s_online_block:
    display_title: 'Pwy sydd ar-lein'
    display_options:
      block_description: 'Pwy sydd ar-lein'
