display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Ailosod
          exposed_sorts_label: 'Sort by'
      use_more_text: More
  block_1:
    display_title: Block
