label: Sylwadau
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Ailosod
          exposed_sorts_label: 'Sort by'
      pager:
        options:
          tags:
            previous: '‹ previous'
            next: 'next ›'
            first: '« first'
            last: 'last »'
          expose:
            items_per_page_label: 'Items per page'
            offset_label: Offset
      fields:
        subject:
          label: Subject
        name:
          label: Author
        entity_id:
          label: 'Posted in'
        changed:
          label: Updated
        operations:
          label: Gweithrediad
      filters:
        subject:
          expose:
            label: Subject
        langcode:
          expose:
            label: Language
      title: Sylwadau
      empty:
        area_text_custom:
          content: 'No comments available.'
      use_more_text: more
  page_published:
    display_title: 'Published comments'
    display_options:
      menu:
        title: Sylwadau
  page_unapproved:
    display_options:
      filters:
        subject:
          expose:
            label: Subject
        langcode:
          expose:
            label: Language
      fields:
        subject:
          label: Subject
        name:
          label: Author
        entity_id:
          label: 'Posted in'
        changed:
          label: Updated
        operations:
          label: Gweithrediad
