label: Content
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Ailosod
          exposed_sorts_label: 'Sort by'
      fields:
        title:
          label: Title
        name:
          label: Author
        status:
          label: Statws
          settings:
            format_custom_true: Published
        changed:
          label: Updated
        operations:
          label: Gweithrediad
      filters:
        title:
          expose:
            label: Title
        status:
          expose:
            label: Statws
          group_info:
            group_items:
              1:
                title: Published
        langcode:
          expose:
            label: Language
      title: Content
  page_1:
    display_options:
      menu:
        title: Content
      tab_options:
        title: Content
    display_title: Page
