display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Ailosod
      fields:
        status:
          label: Statws
        operations:
          label: Gweithrediad
      filters:
        status:
          expose:
            label: Statws
