label: 'Pwy sy''n newydd'
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Ceisio
          reset_button_label: Ailosod
          exposed_sorts_label: 'Dosbarthu drwy'
      title: 'Pwy sy''n newydd'
  block_1:
    display_title: 'Pwy sy''n newydd'
    display_options:
      block_description: 'Pwy sy''n newydd'
      block_category: Defnyddiwr
