session:
  parameter: language
url:
  source: path_prefix
  prefixes:
    en: en
    cy: cy
    la: la
  domains:
    en: ''
    cy: ''
    la: ''
selected_langcode: site_default
_core:
  default_config_hash: uEePITI9tV6WqzmsTb7MfPCi5yPWXSxAN1xeLcYFQbM
