id: species
label: 'Species migrations'
description: 'Species migrations from Llen Natur data.'
source_type: 'CSV files'
shared_configuration:
  source:
    plugin: csv
    path: /app/web/modules/custom/termau_migrate/data/species.csv
    delimiter: ','
    enclosure: '"'
    header_offset: 0
    ids:
      - id
    fields:
      -
        name: id
        label: 'Unique Id'
      -
        name: latin
        label: 'Latin name'
dependencies:
  enforced:
    module:
      - migrate_source_csv
