# Migration configuration for species content.
id: species_node
label: Welsh species
migration_group: species
migration_tags:
  - termau
  - species
source:
  plugin: species_content
destination:
  plugin: entity:node